web/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using core;

namespace web.Controllers
{
    public class AccountController : BaseController
    {
        // define services
        private UserTransactionService UserTransactionService { get; set; }

        public AccountController()
        {
            this.UserTransactionService = new UserTransactionService();
        }

        public IActionResult Index()
        {
            // if not logged-in redirect to login page
            if(!CheckAccess())
            {
                return Redirect("/");
            }
            var user = UserTransactionService.GetUser(GetCurrentUser());
            ViewData["FullName"] = $"{user.FirstName} {user.LastName}";
			return View();
        }

        // get user account details
        public IActionResult GetUserAccount()
        {
            if(!CheckAccess())
            {
                return NoAccess();
            }
            var user = UserTransactionService.GetUser(GetCurrentUser());

            return Json(new {
                username = user.Username,
                firstName = user.FirstName,
                lastName = user.LastName
            });
        }

		// get user account details
		public IActionResult GetTransactions(int page)
		{
			if (!CheckAccess())
			{
				return NoAccess();
			}
            var trans = UserTransactionService.GetTransactionsForUser(GetCurrentUser(), page)
                                              .Select(x => new {
										                date = x.Date.ToString("dd MMMM yy hh:mm:ss tt"),
										                type = x.GetTransactionType().ToString(),
										                amount = x.Amount,
										                prevBalance = x.PrevBalance,
										                currentBalance = x.CurrentBalance
										            });

            return Json(trans);
		}

        // get current balance for user
        public IActionResult GetCurrentBalance()
        {
			if (!CheckAccess())
			{
				return NoAccess();
			}
            return Json(UserTransactionService.GetCurrentBalanceForUser(GetCurrentUser()));
        }

		// deposit transactions
        [HttpPost]
        public IActionResult Deposit([FromBody]decimal amount)
		{
			if (!CheckAccess())
			{
				return NoAccess();
			}
            var res = UserTransactionService.Deposit(GetCurrentUser(), amount);
            if(res.Success)
            {
                return SuccessResponse();
            }
            return ErrorResponse(res.Errors);
		}

		// withdraw transaction
        [HttpPost]
        public IActionResult Withdraw([FromBody]decimal amount)
		{
			if (!CheckAccess())
			{
				return NoAccess();
			}
            var res = UserTransactionService.Withdraw(GetCurrentUser(), amount);
			if (res.Success)
			{
				return SuccessResponse();
			}
			return ErrorResponse(res.Errors);
		}
    }
}

web/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using core;
namespace web.Controllers
{
    public class AuthController : BaseController
    {
		[HttpPost]
		public IActionResult Login([FromBody]AuthModels.Login login)
		{
			// login 
			var res = this.Authservice.Login(login.Username, login.Password);
			if (res.Success)
			{
				// set auth key for session
				SetAuth(res.UserId, res.AuthKey);

				return SuccessResponse("/account");
			}
			// return error
			return ErrorResponse(res.Errors);
		}

		[HttpPost]
        public IActionResult Register([FromBody]AuthModels.Register register)
		{
            // check passwords
            if(register.Password != register.ConfirmPassword)
            {
                return ErrorResponse("Passwords not matched.");
            }

            // define user
            var newuser = new core.DbModels.User
            {
                Username = register.Username,
                Password = register.Password,
                FirstName = register.FirstName,
                LastName = register.LastName
            };

			// register user 
            var res = this.Authservice.Register(newuser);
			if (res.Success)
			{
				return SuccessResponse("/");
			}
			// return error
			return ErrorResponse(res.Errors);
		}

        // logout
        public IActionResult Logout()
        {
            this.Authservice.Logout(GetCurrentUser());
            return Redirect("/");
        }

	}
}

web/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using core;
using Microsoft.AspNetCore.Http;

namespace web.Controllers
{
	public abstract class BaseController : Controller
	{
        // cookies
        private string _authCookie = "GB-Auth";
		private string _userCookie = "GB-User";

        // services
		public AuthService Authservice { get; set; }

        // constructor
		public BaseController()
		{
            // set services
			Authservice = new AuthService();
		}

		// write cookies
        protected void WriteCookies(string setting, string settingValue)
		{
            // create server only cookie
            CookieOptions options = new CookieOptions()
            {
                Path = "/",
                HttpOnly = true,
                Secure = false,
                Expires = DateTime.Now.AddHours(1)
            };
            // write
			Response.Cookies.Append(setting, settingValue, options);
		}

        // read cookies
        protected string ReadCookies(string cookieName)
		{
			return Request.Cookies[cookieName];
		}

        // get authentication key
        public string GetAuthKey()
        {
            return ReadCookies(_authCookie);
        }

		// get user id
		public long GetCurrentUser()
		{
            return long.Parse(ReadCookies(_userCookie));
		}

		// set authentication key
        public void SetAuth(long userId, Guid key)
		{
            WriteCookies(_userCookie, userId.ToString());
            WriteCookies(_authCookie, key.ToString());
		}

		// check if user is authenticated
        public bool CheckAccess()
        {
            // check if auth key is valid
            if(Guid.TryParse(GetAuthKey(), out Guid authkey))
            {
                return Authservice.IsAuthenticated(authkey);
            }
            // if here no auth key
            return false;
        }

        // error respose
        public IActionResult ErrorResponse(string error)
        {
            return Json(new
            {
                code = 1,
                text = error
            });
        }
		// error respose
		public IActionResult SuccessResponse(string redirect = "")
		{
			return Json(new
			{
				code = 0,
                redirect = redirect
			});
		}

        // return no access error
        public IActionResult NoAccess()
        {
            return ErrorResponse("No Access");
        }
	}
}

web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace web.Controllers
{
    public class HomeController : BaseController
    {
        public IActionResult Index()
        {
            // go to account screen if logged in already
            if(CheckAccess())
            {
                return Redirect("/account");
            }
            // else show login page
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home - Great Bank";
    ViewData["LoggedIn"] = false;
}

<h1>Welcome to Great Bank!</h1>
<div ng-controller="HomeController" class="well ng-cloak" ng-cloak>
	<h2 ng-if="!status.Register">Login </h2>
    <h2 ng-if="status.Register">Register</h2>
	<span class="text-danger" ng-bind="status.ValidatationErrors"></span>
    <span class="text-success" ng-bind="status.Instructions"></span>
	<div class="row">
        <div class="col-sm-4">
			<form name="frm">
		        <div ng-if="!status.Register">
		            <div class="form-group">
		              <label for="Username">User Name:</label>
		              <input type="text" class="form-control" id="Username" ng-model="model.Username" required>
		            </div>
		            <div class="form-group">
		              <label for="pwd">Password:</label>
		              <input type="password" class="form-control" id="pwd" ng-model="model.Password" required>
		            </div>      
		            <a href="javascript:;;" type="button" class="btn btn-primary" ng-click="login()">Login</a>
		            <a href="javascript:;;" type="button" class="btn btn-link" ng-click="switchScreen(true)">Register</a>
		        </div>      

		        <div ng-if="status.Register">
		            <div class="form-group">
		              <label for="Username">User Name:</label>
		              <input type="text" class="form-control" id="Username" ng-model="model.Username" required>
		            </div>
		            <div class="form-group">
		              <label for="FirstName">First Name:</label>
		              <input type="text" class="form-control" id="FirstName" ng-model="model.FirstName" required>
		            </div>
		            <div class="form-group">
		              <label for="LastName">Last Name:</label>
		              <input type="text" class="form-control" id="LastName" ng-model="model.LastName" required>
		            </div>
		            <div class="form-group">
		              <label for="pwd">Password:</label>
		              <input type="password" class="form-control" id="pwd" ng-model="model.Password" required>
		            </div>
		            <div class="form-group" ng-if="status.Register">
		              <label for="cpwd">Confirm Password:</label>
		              <input type="password" class="form-control" id="cpwd" ng-model="model.ConfirmPassword" required>
		            </div>
		            <div ng-if="!status.Register">      
		                <a href="javascript:;;" type="button" class="btn btn-primary" ng-click="login()">Login</a>
		                <a href="javascript:;;" type="button" class="btn btn-link" ng-click="switchScreen(true)">Register</a>
		            </div>  
		            <a href="javascript:;;" type="button" class="btn btn-primary" ng-click="register()">Register</a>
		            <a href="javascript:;;" type="button" class="btn btn-link" ng-click="switchScreen(false)">Login</a>
		        </div>
		    </form>
		</div>
	</div>

	<pre ng-if="DEBUG">{{model | json}}</pre>
</div>



web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - web</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body ng-app="app">
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Great Bank</a>
				@{
                    if((bool)ViewData["LoggedIn"])
					{
						<ul class="nav navbar-nav navbar-right">
							<li>
	                            <a asp-area="" asp-controller="Auth" asp-action="Logout" >Logout</a>
							</li>
						</ul>
					}
				}
            </div>

        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - GreatBank</p>
        </footer>
    </div>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/angular/angular.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/home-controller.js"></script>
    <script src="~/js/account-controller.js"></script>
		
    @RenderSection("Scripts", required: false)
</body>
</html>